#端口
port: 4566
host: "127.0.0.1"
#弹幕姬前端页面
index: "./web/living room dm.html"
#websocket配置
websocket:
  port: 4545
  path: "/websocket"

plugins:
  default_path: "./plugin"
  others_plugin:
    -

#调试开关，非开发人员勿动
debug: 1

#日志级别
# DEBUG:调试级别
# INFO:一般运行
# WARNING:警告
# ERROR:错误
# CRITICAL:严重错误
# FATAL:致命错误
loglevel: DEBUG

#日志文件
logfile:
  open: 1
  name: "latest-log"