#端口
port: 8083
host: "127.0.0.1"
#弹幕姬前端配置
web:
 - index: "./web/living room dm.html"
 - tku: "./web/tku.html"

# TODO: 未来会考虑GUI功能，现在这里放着
GUI: 0
use_local_plugin: 0
plugins:
 - "ictye_live_dm.plugin.bilibili_dm_plugin"
debug: 0 #调试开关，非开发人员勿动(动吧，随便动（bushi)
dev: 1

#日志级别
# DEBUG:调试级别
# INFO:一般运行
# WARNING:警告
# ERROR:错误
# CRITICAL:严重错误
# FATAL:致命错误
loglevel: INFO

#日志文件
logfile:
  open: 1
  name: "latestlog"