name: pack package
on: 
  push:
    branches:
      - "main"
  workflow_dispatch:
    
jobs:
  pack_win:
    runs-on: windows-latest

    steps:
      - name: check out my code
        uses: actions/checkout@v4
        with:
          ref: "main"
      - name: install python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.10'
      - name: pack
        run: echo "test"
