name: pack test package
on: 
  push:
    branches:
      - "dev"
  workflow_dispatch:
    
jobs:
  pack_win:
    runs-on: windows-latest

    steps:
      - name: check out my code
        uses: actions/checkout@v4
        with:
          ref: "dev"
      - name: install python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.10'
      - name: pack
        run: | 
          &./.github/windows/winpack.ps1

      - name: upload_results
        uses: actions/upload-artifact@v3
        with:
          name: ictye-live-dm
          path: ictye-live-dm.zip