name: pack test package
on: 
  push:
    branches:
      - "main"
  workflow_run:
    workflows: [test]
    types:
      - completed
  workflow_dispatch:
    
jobs:
  pack_win:
    runs-on: windows-latest

    steps:
      - name: check out my code
        uses: actions/checkout@v4
        with:
          ref: "dev"
      - name: install python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.10'
      - uses: ilammy/msvc-dev-cmd@v1.4.1
      - name: pack
        run: | 
          &./.github/windows/winpack.ps1

      - name: upload_ach
        uses: actions/upload-artifact@v3
        with:
          name: ictye-live-dm
          path: ictye-live-dm.zip

      - name: makensis
        uses: joncloud/makensis-action@v4

      - name: upload_installer
        uses: actions/upload-artifact@v3
        with:
          name: ictye-live-dm-installer
          path: ictye-live-dm-installer-x86_64.exe