name: pack package
on: 
  push:
    branches:
      - "main"
      - "dev"
  workflow_dispatch:
    
jobs:
  pack_win:
    runs-on: windows-latest

    steps:
      - name: check out my code
        uses: actions/checkout@v4
        with:
          ref: "main"
      - name: install python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.10'
      - name: Install download tool
        run: dotnet tool install -g dotnetCampus.FileDownloader.Tool

      - name: pack
        run: |
          DownloadFile -h
          rm -r $GITHUB_ACTION_PATH/ictye-live-dm/test

      - name: upload_results
        uses: actions/upload-artifact@v3
        with:
          name: ictye-live-dm
          path: $GITHUB_ACTION_PATH/ictye-live-dm