name: pack test package
on: 
  push:
    branches:
      - "dev"
  workflow_dispatch:
    
jobs:
  pack_win:
    runs-on: windows-latest

    steps:
      - name: check out my code
        uses: actions/checkout@v4
        with:
          ref: "dev"
      - name: install python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.10'
      - name: pack
        run: |
          Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.11.6/python-3.11.6-embed-amd64.zip" -OutFile "$GITHUB_ACTION_PATH/python.zip"
          mkdir $GITHUB_ACTION_PATH/ictye-live-dm/bin
          Expand-Archive -LiteralPath "$GITHUB_ACTION_PATH/python.zip" -DestinationPath "$GITHUB_ACTION_PATH/ictye-live-dm/bin"
          ls -a $GITHUB_ACTION_PATH
          ls -a $GITHUB_ACTION_PATH/ictye-live-dm/
          tree /f $GITHUB_ACTION_PATH



      - name: upload_results
        uses: actions/upload-artifact@v3
        with:
          name: ictye-live-dm
          path: $GITHUB_ACTION_PATH/ictye-live-dm.zip