name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "dev"
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        continue-on-error: true
        with:
          linter: jvm
          version: 2024.1
          use-caches: true
          results-dir: /home/runner/work/_temp/qodana/results
          cache-dir: /home/runner/work/_temp/qodana/caches
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
