name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "dev"
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v4.2.4
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
