name: test
on:
  push:
    branches:
      - "dev"
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: check out my code
        uses: actions/checkout@v4
        with:
          ref: "main"
      - name: install python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.10'
      - name: test
        run: |
          python -m pip install --upgrade pip
          pip install -r $GITHUB_ACTION_PATH/test_requirements.txt
          pytest $GITHUB_ACTION_PATH
